config/routes.rb
Rails.application.routes.draw do
  
  root to: 'sessions#index'
  
  get "sign_up" => 'users#new', as: "sign_up"
  
  get "log_in" => 'sessions#new', as: 'log_in' 
  
  get "logout" => 'sessions#destroy', as: 'log_out' 
  
  get 'userinfo' => "users#userinfo" 
  
  resources :users
  
  namespace :api do
    namespace :v1 do
      resources :users
      resources :clients
      put 'metadata' => "metadata#update"
    end
  end
  
  
  resources :sessions
  
  resources :clients
  
  resources :authorise
  
  resources :token

end

app/models/client.rb
class Client

  include Wisper::Publisher
  
  include Mongoid::Document
  include Mongoid::Timestamps  
  
  embeds_many :authorisations
  
  embeds_many :timestamps
  
  validates_presence_of :name, :redirect_uri
  
  field :name, type: String
  field :client_id, type: String
  field :secret, type: String
  field :redirect_uri, type: String
  field :post_logout_redirect_uri, type: String
  
  #after_save :publish_save_event
  
  def self.with_user_auth(user: nil)
    self.where("authorisations.user_id" => user.id)
  end
  
  
  def create_me(params)
    self.name = params[:name]
    self.client_id = name.downcase.gsub(/ /, "_")
    self.secret = SecureRandom.urlsafe_base64(nil, false)
    self.redirect_uri = params[:redirect_uri]
    self.post_logout_redirect_uri = params[:post_logout_redirect_uri]
    self.save
    publish(:success_client_save_event, self)
  end
  
  
  def update_me(params)
    self.name = params[:name]
    self.redirect_uri = params[:redirect_uri]
    self.post_logout_redirect_uri = params[:post_logout_redirect_uri]
    determine_save_event_state()
  end
    
  def change_credentials
    self.secret = SecureRandom.urlsafe_base64(nil, false)
  end
    
  def get_auth_req(params: nil, user: nil)
    raise if self.redirect_uri != params[:redirect_uri]
    auth = self.authorisations.where(user_id: user.id).gte(expires_in: Time.now + 10.seconds).first
    if auth
      auth
    else      
      auth = Authorisation.create_it(params: params, user: user)
      self.authorisations << auth
      self.timestamps << Timestamp.new_state(state: :create_auth_req_time , name: :auth_req)
      self.save
      auth
    end
  end
  
  def last_auth_request(user: nil)
    auth = self.authorisations.last
    auth.add_user(user: user) if user
    self.save
    auth
  end
  
  
  def get_authorisation(code: nil)
    self.authorisations.where(auth_code: code).first
  end

  def get_access_authorisation(access_code: nil)
    self.authorisations.where(access_code: access_code).first
  end

  
  def provide_access(auth)
    auth.create_access_token
    self.timestamps << Timestamp.new_state(state: :provide_access_token_time, name: :provide_access_token)
    save
    auth
  end
  
  def get_user(auth: nil)
    self.timestamps << Timestamp.new_state(state: :get_user_time, name: :get_user_info)
    save
    raise if !auth
    auth.user
  end
  
  private
    
    
  def determine_save_event_state
    if self.valid?
      self.save
      publish(:success_client_save_event, self)
    else
      publish(:failed_client_save_event, self)
    end
  end
      
end

app/controllers/api/v1/clients_controller.rb
class Api::V1::ClientsController < Api::ApplicationController
  
  def index
    @clients = Client.all
  end
  
  def show
    @client = Client.find(params[:id])
  end
  
  def update
    
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def index
    @clients = Client.all
  end
  
  def new
    @client = Client.new
  end
  
  def show 
    @client = Client.find(params[:id])
  end
  
  def create
    client = Client.new
    client.subscribe(self)    
    client.create_me(params[:client])
  end
  
  def edit
    @client = Client.find(params[:id])
  end
  
  def update
    client = Client.find(params[:id])
    client.subscribe(self)    
    client.update_me(params[:client])
  end
  
  def success_client_save_event(client)
    respond_to do |f|
      f.html { redirect_to clients_path}
    end
  end
  
  def failed_client_save_event(client)
    @client = client
    respond_to do |f|
      f.html { render '_form'}
    end

  end
  
end

app/views/clients/_form.html.erb
<%= form_for(@client, html: { class: "custom"}) do |f| %>
   <div class="row">
     <div class="small-2 columns">
       <%= f.label :name, class: "right inline"%>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :name %>
     </div> 
   </div>
   <div class="row">
     <div class="small-2 columns">
       <%= f.label :redirect_uri, class: "right inline"%>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :redirect_uri %>
     </div> 
   </div>
   <div class="row">
     <div class="small-2 columns">
       <%= f.label :logout_redirect_uri, class: "right inline"%>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :post_logout_redirect_uri %>
     </div> 
   </div>
   <div class="row">
     <div class="small-10 small-offset-2 columns">
       <%= f.submit 'Submit', :class => 'button small' %>
     </div>
   </div>
<% end %>

app/views/clients/edit.html.erb
<%= render partial: 'form' %>

app/views/clients/index.html.erb
<%= link_to 'New Client', new_client_path, class: "button"%>
<table class="table">
   <thead>
     <tr>
       <th>Name</th>
       <th>Client ID</th>
       <th>Secret</th>
       <th>Redirect URL</th>              
       <th>Actions</th>      
     </tr>
   </thead>
   <tbody>
      <% for client in @clients %>         
         <tr>
            <td>
               <%= link_to client.name, client_path(client)%>
            </td>
            <td><%= client.client_id %></td>
            <td><%= client.secret %></td>
            <td><%= client.redirect_uri %></td>            
            <td>
               <%= link_to "Show",  client_path(client), class: "btn btn-default"%>
               <%= link_to "Edit",  edit_client_path(client), class: "btn btn-default"%>               
            </td>
         </tr>
      <% end %>
   </tbody>
</table>

app/views/clients/new.html.erb
<%= render partial: 'form' %>

app/views/clients/show.html.erb
<h1><%= @client.name%></h1>
<p>Id: <%= @client.client_id %></p>
<p>Secret: <%= @client.secret %></p>
<p>Redirect_uri: <%= @client.redirect_uri %></p>

<% for event in @client.timestamps %>
   <p>Time: <%= event.timestamp %>Name: <%= event.name %></p>   
<% end %>