config/routes.rb
Rails.application.routes.draw do
  
  root to: 'sessions#index'
  
  get "sign_up" => 'users#new', as: "sign_up"
  
  get "log_in" => 'sessions#new', as: 'log_in' 
  
  get "logout" => 'sessions#destroy', as: 'log_out' 
  
  get 'userinfo' => "users#userinfo" 
  
  resources :users
  
  namespace :api do
    namespace :v1 do
      resources :users
      resources :clients
      put 'metadata' => "metadata#update"
    end
  end
  
  
  resources :sessions
  
  resources :clients
  
  resources :authorise
  
  resources :token

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Identity" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="icon-bar five-up">
      <a class="item">
        <i class="fi-home"></i>
        <label>Home</label>
      </a>
      <%= link_to(clients_path) do %>
        <i class="fi-torso"></i>
        <label>Clients</label>
      <% end %>            
      <%= link_to(users_path, class: "item") do %>
        <i class="fi-torso"></i>
        <label>Users</label>
      <% end %>        

      
      
      <% if @current_user %>
        <%= link_to(session_path(@current_user, local: true), method: :delete) do %>
          <i class="fi-lock"></i>
          <label>Logout <%= @current_user.name%></label>
        <% end %>      
      <% else %>
        <%= link_to(log_in_path) do %>
          <i class="fi-unlock"></i>
          <label>Login</label>
        <% end %>            
        <%= link_to(sign_up_path) do %>
          <i class="fi-unlock"></i>
          <label>Signup</label>
        <% end %>            
      <% end %>
    </div>
    
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ID" %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Identity</a>
        </div>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Clients <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List", clients_path %></li>
                <li><%= link_to "New", new_client_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if @current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_user.name %><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Logout", session_path(@current_user, local: true), method: :delete %></li>
                </ul>
              </li>
            <% else %>              
              <li><%= link_to 'login', log_in_path%></li>
              <li><%= link_to 'Sign Up', sign_up_path%></li>
            <% end %>
          </ul>          
      </div>
    </div>
  
          </ul>          
        </div>
      </div>
    </div>
  </header>

<div class="container master-container">
    <ul class="breadcrumb">
      <%= yield :breadcrumb %>
    </ul>

    <% if notice %>
      <div class="alert alert-success fade in" data-alert="alert">
        <a class="close" data-dismiss='alert' href="#">×</a>
        <p><%= notice %></p>
      </div>
    <% end %>

    <%= yield %>
    
  </div>
  </body>
</html>